export const ActionType = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  INCREMENT: "INCREMENT",
  DECREMENT: "DECREMENT",
  ALL_CART_REMOVE: "ALL_CART_REMOVE",
  SELECTED_ITEMS_IDS: "SELECTED_ITEMS_IDS",
  REMOVE_SELECTED_PRODUCT_IDS: "REMOVE_SELECTED_PRODUCT_IDS",
  ALL_REMOVE_SELECTED_PRODUCT_IDS: "ALL_REMOVE_SELECTED_PRODUCT_IDS",
};
